# Generated by Django 2.2.7 on 2019-11-16 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='doc_control.Document'),
        ),
        migrations.AlterField(
            model_name='update',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
