# Generated by Django 2.2.7 on 2019-11-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='updated_by',
        ),
    ]
