# Generated by Django 2.2.7 on 2019-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0002_remove_update_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='updated_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
