# Generated by Django 2.2.7 on 2019-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0002_auto_20191119_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='drawing',
            field=models.CharField(max_length=500),
        ),
    ]
