# Generated by Django 2.2.7 on 2019-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0003_auto_20191116_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='decription',
            field=models.CharField(max_length=50),
        ),
    ]
