# Generated by Django 2.2.7 on 2019-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0003_auto_20191116_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='update_decription',
            new_name='update_description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='decription',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='drawing',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
    ]
