# Generated by Django 2.2.7 on 2019-11-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0003_auto_20191119_1426'),
        ('doc_control', '0003_auto_20191119_1508'),
    ]

    operations = [
    ]
