# Generated by Django 2.2.7 on 2019-11-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0004_auto_20191118_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='decription',
            new_name='description',
        ),
    ]
