# Generated by Django 2.2.7 on 2019-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_control', '0005_auto_20191118_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='update_decription',
            new_name='update_description',
        ),
    ]
